name: Build JNIAnlyzer
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Setup Java'
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          java-package: jdk
          architecture: x64

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: 'Download latest Ghidra'
        run: |
          pip install -U pip
          pip install -U requests
          pip install -U beautifulsoup4
          python ./scripts/fetch-ghidra-latest.py

      - name: 'Extract Ghidra'
        run: |
          7z x /tmp/ghidra.zip -o/tmp/ghidra

      - name: 'Gradle Build'
        run: |
          cd JNIAnalyzer
          gradle -PGHIDRA_INSTALL_DIR=$(find /tmp/ghidra/ -mindepth 1 -maxdepth 1 -type d)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: JNIAnalyzer/dist/*.zip
