name: Build JNIAnlyzer
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Setup Java'
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          java-package: jdk
          architecture: x64

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: 'Download latest Ghidra'
        run: |
          pip install -U pipg
          pip install -U requests
          pip install -U beautifulsoup4
          python ./scripts/fetch-ghidra-latest.py

      - name: 'Extract Ghidra'
        run: |
          7z x ghidra.zip -oghidra

      - name: 'Gradle Build'
        run: |
          gradle -PGHIDRA_INSTALL_DIR=./ghidra
